/**
 * Created by 蚂蚱
 */
var languagePack = {
	"复活节限定": "Easter",
	"情人节限定": "Valentine's day",
    "买二得三专区": 'Order 2 boxes, 3d one is for free',
    "号码错误": 'telphone error',
    "好运饼": 'lucky cake',
    "充值(套餐充值有赠送)": 'Recharge',
    "圣诞限定": "Christmas time",
    "请选择配送城市": 'Please select the delivery City',
    "请选择套餐": 'Please choose the combo menu',
    "套餐充值": 'Package recharge',
    "储值卡充值": 'Pre-paid card',
    "储值卡券码": 'Code NO',
    "优惠金额": 'Discount amount',
    "满": 'Free delivery over ',
    "元包邮": 'RMB',
    "请输入姓名": 'Enter your name',
    "添加优惠券": 'Add coupons',
    "规格": 'Standard',
    "使用余额": 'Use balance',
    "共": 'Total',
    "商品金额": 'Goods amount',
    "优惠券": 'Coupon',
    "实付款": 'Actual payment',
    "搜索商品": 'Search goods',
    "更多": 'More',
    "全部分类": 'Category',
    "购物车": 'Cart',
    "个人中心": 'Profile',
    "套餐": 'Package',
    "巧克力": 'Chocolates',
    "甜点": 'Dessert',
    "曲奇": 'Cookies',
    "面包/吐司/丹麦": 'Bread/Toast/Danish',
    "马卡龙": 'Macarons',
    "组合": 'Combination',
    "销量": 'Sales',
    "加入购物车": 'Add to cart',
    "加入购物车成功": 'Add successfully',
    "其他推荐": 'Other recommendations',
    "全选": 'Select all',
    "结算": 'Order',
    "购物车是空的": 'The shopping cart is empty',
    "快去添加商品吧": 'Go ahead and add the goods',
    "创建订单": 'Create order',
    "请选择": 'Please select',
    "无可用": 'Not available',
    "运费": 'Freight',
    "我的收货地址": 'My delivery address',
    "+添加收货地址": '+ Add address',
    "手机号码": 'Phone number',
    "编辑发票": 'Edit invoice',
    "我的优惠券": 'My coupons',
    "订单详情": 'Order details',
    "我的余额": 'My balance',
    "充值": 'Recharge',
    "全部订单": 'Full order',
    "所有": 'All',
    "充值记录": 'Recharge record',
    "消费记录": 'Consumption record',
    "余额充值": 'Recharge',
    "余额消费": 'Consumption',
    "请选择以下充值套餐": 'Please select the following recharge packages',
    "充值金额为": 'Recharge amount',
    "可使用": 'Available',
    "已使用": 'Used',
    "已过期": 'Expired',
    "法派1855微商城": "Wechat mall of Comptoirs de france",
    "法派1855微商城，美味新鲜送到家": "Comptoirs de france the french taste at home.",
    '微信订购纯正法式烘焙美食，满200顺丰包邮哦': "Order our french authentic products and enjoy a free delivery over 200rmb",
    "我的订单": "My Orders",
    "商品详情": "Description",
    "立即购买": "Order",
    "订单商品": "Items",
    "注册微会员": "Register",
    "温馨提示：09:00之前下单，当天配送或指定时间配送，09:00以后下单，第二天配送或指定时间配送。因蛋糕为纯手工制作，所以实物与标注尺寸会有略微差异": "Tips:Order before 09:00am，we offer same-day delivery or on the date you ask for,Order after 09:00am，receive the cake next day or on the date you ask for. Because every cake is handmade, the shape can be slightly different.",
    "请选择配送方式": "Choose Delivery Method",
    "门店自提": "Pick up in our shop",
    "送货上门": "Shipped home",
    "快递到家": "Shipped home",
    "请选择收货地址": "Please select the receiving address",
    "请选择取货门店": "Please select the store",
    "确定": "OK",
    "取消": "Cancel",
    "预定信息": "Pick up information",
    "手机号": "Cellphone",
    "请输入手机号码": "Enter your cellphone",
    "取货日期": "Pick up date",
    "请选择取货日期": "Choose pick up date",
    "取货时间": "Pick up time",
    "选择时间段": "Choose delivery time",
    "配送信息": "Delivery information",
    "配送日期": "Delivery date",
    "请选择配送日期": "Choose delivery date",
    "配送时间": "Delivery time",
    "生日牌": "Birthday Card",
    "生日巧克力牌": "Birthday Chocolate sign",
    "请输入你需要写在巧克力牌上的文字，如：生日快乐": "Please enter your birthday greetings,such as:Happy Birthday",
    "需要生日牌": "Need Birthday Card",
    "需要生日巧克力牌": "Need Birthday Chocolate sign",
    "另收10.00元": "￥10.00RMB",
    "备注": "Remark",
    "如有疑问，请联系客服": "Please contact our service number any time for any question you might have",
    "合计": "Total",
    "提交订单": "Submit",
    "订单编号": "Order SN",
    "订单时间": "Order Time",
    "订单状态": "Status",
    "配送方式": "Delivery Method",
    "备注信息": "Remark",
    "取货门店": "Pick up shop",
    "收货地址": "Delivery Address",
    "取消订单": "Cancel",
    "立即付款": "Pay",
    "立即支付": "Pay",
    "待付款": "Unpaid",
    "待发货": "Unshipped",
    "待收货": "Shipped",
    "已完成": "Completed",
    "订单取消": "Canceled",
    "订单删除": "Deleted",
    "请填写手机号码": "Please fill in the phone number",
    "请选择日期": "Please select a date",
    "请选择时间段": "Please select a time period",
    "请填写备注信息": "Please fill in the remark",
    "手机号码错误": "Cellphone number error",
    "订单已取消": "Cancelled",
    "订单已付款": "Paid",
    "已确认收货": "Receipt",
    "订单已删除": "Deleted",
    "回到商城逛逛": "Back to the mall",
    "返回首页": "HomePage",
    "付款成功": "Payment success",
    "您已成功预定": "You have successfully booked",
    "添加收货地址": "Add address",
    "默认地址": "Default address",
    "设为默认": "Set as default",
    "编辑": "edit",
    "删除": "delete",
    "编辑收货地址": "Edit receiving address",
    "收货人": "Consignee",
    "配送城市": "Distribution city",
    "配送地区": "Distribution area",
    "详细地址": "Address",
    "请填写街道信息": "Please fill in the street information",
    "请选择配送地区": "Please select the distribution area",
    "已付款": "Already paid",
    "已发货": "Already shipped",
    "确认收货": "Confirm receipt",
    "订单已完成": "Completed",
    "删除订单": "Delete order",
    "请填写姓名": "Please fill in your name",
    "请选择一个商品": "Please choose a cake before",
    "保存": "Save",
    "姓名": "Name",
    "11位手机号码": "Correct cell phone number",
    "北京市": "Beijing City",
    "法派1855北京和睦家医院2店": "B.J.U Shop 2",
    "北京市朝阳区将台路2号北京和睦家医院1号急诊楼1层": "Building 2, 2Jiangtai Road, Beijing United Family Hospital, Chaoyang District",
    "法派1855北京和睦家医院3店": "B.J.U Shop 3",
    "北京市朝阳区将台路2号北京和睦家医院新楼一层3号楼1层": "Building 3, 2Jiangtai Road, Beijing United Family Hospital, Chaoyang District Beijing",
    "法派1855融科中心店": "Raycom InforTech Park",
    "北京市海淀区北京市海淀区科学院南路2号融科资讯中心C座地下一层C-012": "B1 –C 012, CBlock Raycom InforTach Park No2 Kexueyuan South Road Haidian District",
    "法派1855天津和睦家医院店": "Tianjin United Family Hospital",
    "天津市河西区潭江道天潇园22号": "22 TianxiaoYuan, Tanjiang Road Hexi District, Tianjin",
    "法派1855和睦家医院店": "B.J.U Shop 1",
    "北京市朝阳区将台路2号北京和睦家医院新楼一层": "Building 1, 2Jiangtai Road, Beijing United Family Hospital, Chaoyang District Beijing",
    "法派1855朝阳公园店": "Chaoyang Park",
    "北京市朝阳区朝阳公园南路1-15号": "1-15 ChaoyangPark South Road, Chaoyang District Beijing",
    "法派1855幸福村店": "Xingfucun Shop",
    "北京市朝阳区幸福村中路55-1号杰座大厦1楼(近春秀路)": "No55-1,XingFuCun Mid Road, Chaoyang District Beijing",
    "法派1855香江店": "Riviera Plaza",
    "北京市朝阳区来广营东路5号": "5 LaiguangyingEast Road, Second Floor (east side), Chaoyang District Beijing",
    "法派1855丽都店": "Lido",
    "北京市朝阳区将台路乙2号海润国际公寓底商(近朝阳公园)": "First Floor Business Building No 5, Harirun IntlApartment, B 2 Jiangtai Road Chaoyang District Beijing",
    "法派1855顺义欧陆广场店": "ShunyiEuroplaza",
    "北京市顺义区天竺镇裕祥路99号欧陆广场L111号(新国展对面)": "Room L 111, 99 Yu Xiang Road, Tianzhou TownShunyi District Beijing",
    "法派1855东湖别墅店": "EastLake Villas",
    "北京市东城区东直门外大街35号东湖别墅大堂": "First Floor East Lake Club, 35 Dongzhimenwai Dajie,Dongcheng District Beijing",
    "商品库存不足，请重新选择": "Inventory shortage, please re selection",
    "请输入巧克力生日牌上的文字": "enter the text on the chocolate birthday card",
    "请输入发票抬头": "enter invoice header",
    "请输入您的其他需求": "enter your other needs",
    "生日牌信息": "Birthday card information",
    "发票信息": "Invoice information",
    "其他信息": "Other information",
    "需要发票": "Need Invoice",
    "发票抬头": "Invoice Title",
    "请编辑发票信息": "Please edit invoice information",
    "发票类型": "Invoice type",
    "增值税普通发票": "Ordinary invoice",
    "增值税专用发票": "VAT invoice",
    "开票金额不包括优惠券支付部分": "Invoice amount does not include coupon payment section",
    "个人": "personal",
    "单位": "Company",
    "发票内容": "Invoice content",
    "食品": "Food",
    "蛋糕": "Cakes",
    "请输入单位名称": "Please enter the name of the unit",
    "请输入纳税人识别码": "Please enter the taxpayer identification code",
    "请输入注册地址": "Please enter a registered address",
    "请输入注册电话": "Please enter a phone number",
    "注册电话错误": "Registration error",
    "请输入开户银行": "Please enter an account bank",
    "请输入银行账户": "Please enter a bank account",
    "填写核对公司信息": "Fill in company information",
    "单位名称": "Unit name",
    "纳税人识别码": "Taxpayer identification code",
    "注册地址": "Registered address",
    "注册电话": "Registered phone",
    "开户银行": "Bank",
    "银行账户": "Bank account",
    "优惠": "coupons",
    "使用优惠": "use coupons",
    "不使用优惠券": "do not use coupons",
    "可用优惠券": "available coupons",
    "有效期": "limited period",
    "请输入券码": "Please enter the code",
    "添加券码": "Add coupon code",
    "添加": "add",
    "语言": "Language",
    "中文": "Chinese",
    "英文": "English",
    "首页": "Home",
    "品牌故事": "STORY",
    "蛋糕预定": "ORDER NOW",
    "提供服务": "OUR SERIVE",
    "企业定制": "ENTERPRISE",
    "关于我们": "ABOUT US",
    "获得奖项": "Awards",
    "订单导航": "OEDERING GUIDE",
    "联系我们": "CONTACT US",
    "关注我们": "FOLLOW US",
    "门店详情": "OUR STORES",
    "北京": "BeiJing",
    "选择地区": "Select area",
    "到家": "DaoJia",
    "优餐送": "You Can Song",
    "食派士": "Sherpa's",
    "百度外卖": "Baidu Waimai",
    "饿了么": "eleme",
    "美团外卖": "Meituan Waimai",
    "锦食送": "Jingshisong",
    "配送说明": "Delivery Note",
    "购买数量": "Purchase quantity",
    "请使用微信扫描二维码，进入法派微信商城": "Please use WeChat scanning two-dimensional code, into the law to send WeChat mall",
    "公司名称": "Company name",
    "公司地址": "Company district",
    "联系人": "Contact person",
    "联系电话": "Contact mobile",
    "公司人数": "Number of companies",
    "留言内容": "Remark",
    "请输入公司名称": "Enter the company name",
    "请输入联系人姓名": "Enter the contact name",
    "请输入联系电话": "Enter the contact number",
    "请输入公司人数": "Enter the number of companies",
    "咨询业务内容": "Consulting business content",
    "我们选择高品质的成分在世界各地，结合传统法国食谱与现代烘焙技术。": "We select high quality ingredients from all over the world.Combine traditional French recipes with modern baking techniques.",
    "所有这些产品都是手工制作的，该公司仅使用法国和德国的优质原料。": "All these products are handmade and the company utilized only pre- mium quality raw products from France and Germany.",
    "我们相信为客户提供面包店，糕点店的最高标准，我们的目标是确保为所有客户提供质量和保证。": "We believes  in providing customers with the highest standard in bakery, pastry,We aim at insuring quality andconsistency to all our clients.",
    "从A到Z生产优质的健康产品，为客户提供真正的法国体验": "To produce from A to Z quality healthy products and deliver a true French experience to our customers"
};